name: Upload Site to http://staging.covidactnow.org.s3-website-us-west-1.amazonaws.com

on:
  push:
    branches:
    - staging

jobs:
  build-deploy:
    name: Build_and_Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # will run `yarn build` command
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'staging.covidactnow.org'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'build/'      # optional: defaults to entire repository
