name: Update to new data snapshot

on:
  workflow_dispatch:
    inputs:
      snapshot_id:
        description: The snapshot number to generate a website PR for.
        required: true

env:
  AWS_S3_BUCKET: content.covidactnow.org
  SNAPSHOT_ID: ${{ github.event.inputs.snapshot_id }}
  # Used in the shared images URL and in the PR branch.
  RUN_ID: ${{ github.event.inputs.snapshot_id }}-${{github.run_number}}
  # 4gb might be overkill, the default is 512mb, but this works.
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  update-data-snapshot:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Verify snapshot provided
        if: ${{ !env.SNAPSHOT_ID }}
        run: 'echo "Missing client_payload parameter: snapshot_id" ; exit 1'
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - run: yarn install

      # Copy region-overrides.json file from backend repo.
      - run: curl https://raw.githubusercontent.com/act-now-coalition/covid-data-model/main/data/region-overrides.json > src/cms-content/region-overrides/region-overrides.json

      # Update snapshot URL and regenerate map colors.
      - run: 'echo "{ \"data_url\": \"https://data.covidactnow.org/snapshot/${{env.SNAPSHOT_ID}}/v2/\" }" | python -mjson.tool > src/assets/data/data_url.json'
      - run: yarn update-location-summaries

      # Generate new county-history-data.json file (for animap project).
      - run: yarn generate-county-history-data

      # Generate new data coverage summary file (For data coverage table).
      - run: yarn update-data-coverage-summary

      # Deploy https://content.covidactnow.org/animap/county-history-data.json
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: '--acl public-read --follow-symlinks --delete'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CONTENT_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CONTENT_AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: scripts/county_history_data/out
          DEST_DIR: animap

      - run: 'echo "{ \"share_image_url\": \"https://covidactnow-prod.web.app/share/${{env.RUN_ID}}/\" }" | python -mjson.tool > src/assets/data/share_images_url.json'

      # Generate Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: 'bump-snapshot-${{env.RUN_ID}}'
          commit-message: |
            Update to data snapshot ${{env.SNAPSHOT_ID}}.

            * Regenerate summary files.
            * Point at new share images URL.
          title: Update to data snapshot ${{env.SNAPSHOT_ID}}
          body: |
            Update to data snapshot ${{env.SNAPSHOT_ID}}.

            * Regenerate summary files.
            * Point at new share images URL.

      - name: Wait for Preview URL to be live
        run: npx wait-on -t 120000 https://covidactnow-git-bump-snapshot-${{env.RUN_ID}}-act-now-coalition.vercel.app/compare/ || echo 'Preview URL failed to load.'

      - name: Read slack-summary.txt
        id: slack_summary
        run: echo ::set-output name=text::$(cat scripts/slack-summary.txt)
      - name: Slack notification
        if: job.status != 'success'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DAILY_DEPLOYS }}
          STATUS: ${{job.status}}
        uses: Ilshidur/action-slack@fb92a78a305a399cd6d8ede99d641f2b9224daf3
        with:
          args: 'update-snapshot failed: {{STATUS}}'
      - name: Slack notification
        if: job.status == 'success'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DAILY_DEPLOYS }}
          STATUS: ${{job.status}}
        uses: Ilshidur/action-slack@fb92a78a305a399cd6d8ede99d641f2b9224daf3
        with:
          args: |
            PR to update the website to snapshot ${{env.SNAPSHOT_ID}} (with updated map colors and share images) is available.
            PR: https://github.com/act-now-coalition/covid-act-now-website/pull/${{env.PULL_REQUEST_NUMBER}}
            Preview: https://covidactnow-git-bump-snapshot-${{env.RUN_ID}}-act-now-coalition.vercel.app/
            Compare: https://covidactnow-git-bump-snapshot-${{env.RUN_ID}}-act-now-coalition.vercel.app/internal/compare/
            ${{steps.slack_summary.outputs.text}}
