name: Update to new data snapshot (regenerate colors and sharing images).

on:
  repository_dispatch:
    types: update-data-snapshot

env:
  AWS_S3_BUCKET: content.covidactnow.org
  BRANCH: ${{ github.event.client_payload.branch }}
  SNAPSHOT_ID: ${{ github.event.client_payload.snapshot_id }}
  IMAGES_ID: ${{ github.event.client_payload.snapshot_id }}-${{github.run_number}}

jobs:
  update-data-snapshot:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Verify snapshot provided
        if: ${{ !env.SNAPSHOT_ID }}
        run: 'echo "Missing client_payload parameter: snapshot_id" ; exit 1'
      - name: Verify branch provided
        if: ${{ !env.BRANCH }}
        run: 'echo "Missing client_payload parameter: branch" ; exit 1'
      - uses: actions/checkout@v2
        with:
          repository: covid-projections/covid-projections
          ref: '${{ env.BRANCH }}'
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      # Update snapshot URL and regenerate map colors.
      - run: yarn install
      - run: 'echo "{ \"data_url\": \"https://data.covidactnow.org/snapshot/${{env.SNAPSHOT_ID}}/\" }" > src/assets/data/data_url.json'
      - run: yarn update-calculated-interventions

      # Generate Share Images and Upload to S3
      - run: yarn start &
      # TODO: Find better way to wait for webserver to start up.
      - run: sleep 15
      - run: yarn generate-share-images
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: '--acl public-read --follow-symlinks --delete'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: scripts/generate_share_images/output
          DEST_DIR: share/${{env.IMAGES_ID}}
      - run: 'echo "{ \"share_image_url\": \"https://content.covidactnow.org/share/${{env.IMAGES_ID}}/\" }" > src/assets/data/share_images_url.json'

      # Generate Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          branch: 'bump-snapshot-${{env.SNAPSHOT_ID}}'
          branch-suffix: random
          commit-message: >
            Update to data snapshot ${{env.SNAPSHOT_ID}}.

            * Regenerate calculated interventions files.
            * Point at updated share images.
          title: Update to data snapshot ${{env.SNAPSHOT_ID}}
          body: >
            Update to data snapshot ${{env.SNAPSHOT_ID}}.

            * Regenerate calculated interventions files.
            * Point at updated share images.
